import { useState, useEffect } from "react";
import { SectionCard, FormField, btnStyle, inputStyle, toast } from "../../components/ui/UI.jsx";

export default function TwoFactorSection({ addAudit }) {
  const [enabled, setEnabled] = useState(false);
  const [setupStep, setSetupStep] = useState(0);
  const [code, setCode] = useState("");

  useEffect(() => {
    setEnabled(localStorage.getItem("mock_2fa_enabled") === "true");
  }, []);

  const enable2FA = () => {
    if (code.length !== 6) {
      toast("Please enter a valid 6-digit code", "error");
      return;
    }
    
    // Mock validation
    localStorage.setItem("mock_2fa_enabled", "true");
    setEnabled(true);
    setSetupStep(0);
    setCode("");
    addAudit("Security", "2FA Enabled", "User enabled Two-Factor Authentication");
    toast("Two-Factor Authentication enabled successfully!");
  };

  const disable2FA = () => {
    localStorage.removeItem("mock_2fa_enabled");
    setEnabled(false);
    addAudit("Security", "2FA Disabled", "User disabled Two-Factor Authentication");
    toast("Two-Factor Authentication disabled");
  };

  return (
    <div style={{ display: "grid", gridTemplateColumns: "1fr", gap: 16 }}>
      <SectionCard>
        <div style={{ fontWeight: 700, fontSize: 14, marginBottom: 16 }}>Two-Factor Authentication (2FA)</div>
        
        {enabled ? (
          <div style={{ padding: 16, background: "var(--success-dim)", border: "1px solid var(--success)", borderRadius: 8 }}>
            <div style={{ fontWeight: 600, color: "var(--success)", fontSize: 14, marginBottom: 8, display: "flex", alignItems: "center", gap: 8 }}>
              ✅ 2FA is currently enabled
            </div>
            <div style={{ fontSize: 13, color: "var(--text)", marginBottom: 16 }}>
              Your account is protected. You will be required to enter a code from your authenticator app when logging in from new devices.
            </div>
            <button style={{ ...btnStyle("ghost", "sm"), color: "var(--danger)", border: "1px solid var(--danger)" }} onClick={disable2FA}>
              Disable 2FA
            </button>
          </div>
        ) : (
          <div>
            <div style={{ fontSize: 13, color: "var(--text-muted)", marginBottom: 20 }}>
              Add an extra layer of security to your account. Once enabled, you'll need to enter a unique 6-digit code generated by an app on your mobile device whenever you sign in.
            </div>

            {setupStep === 0 && (
              <button style={btnStyle("primary")} onClick={() => setSetupStep(1)}>Set up Authenticator App</button>
            )}

            {setupStep === 1 && (
              <div style={{ padding: 20, background: "var(--surface-raised)", borderRadius: 8, border: "1px solid var(--border)", display: "flex", flexDirection: "column", gap: 16 }}>
                <div style={{ fontWeight: 600, fontSize: 14 }}>Step 1: Scan the QR Code</div>
                <div style={{ fontSize: 13, color: "var(--text-muted)" }}>
                  Use an authenticator app like Google Authenticator, Authy, or 1Password to scan this QR code.
                </div>
                
                {/* Mock QR Code */}
                <div style={{ width: 160, height: 160, background: "#fff", display: "flex", alignItems: "center", justifyContent: "center", borderRadius: 8, alignSelf: "center", margin: "10px 0" }}>
                  <svg width="120" height="120" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
                    <rect width="100" height="100" fill="#fff"/>
                    <path d="M10 10h30v30H10zM15 15h20v20H15zM60 10h30v30H60zM65 15h20v20H65zM10 60h30v30H10zM15 65h20v20H15z" fill="#000"/>
                    <path d="M45 10h10v10H45zM45 25h10v10H45zM45 40h10v10H45zM10 45h10v10H10zM25 45h10v10H25zM60 45h10v10H60zM75 45h10v10H75zM85 45h10v10H85zM45 60h10v10H45zM45 75h10v10H45zM60 60h30v10H60zM60 75h10v20H60zM75 75h15v10H75z" fill="#000"/>
                  </svg>
                </div>
                <div style={{ fontSize: 12, textAlign: "center", color: "var(--text-muted)" }}>
                  Or enter this code manually: <strong>JBSWY3DPEHPK3PXP</strong>
                </div>

                <div style={{ borderTop: "1px solid var(--border)", paddingTop: 16, marginTop: 8 }}>
                  <div style={{ fontWeight: 600, fontSize: 14, marginBottom: 8 }}>Step 2: Verify the Code</div>
                  <div style={{ display: "flex", gap: 12, alignItems: "flex-end" }}>
                    <div style={{ flex: 1 }}>
                      <FormField label="6-Digit Authenticator Code">
                        <input style={inputStyle} value={code} onChange={e => setCode(e.target.value)} placeholder="000000" maxLength={6} />
                      </FormField>
                    </div>
                    <button style={{ ...btnStyle("primary"), height: 38, marginBottom: 2 }} onClick={enable2FA}>Verify & Enable</button>
                    <button style={{ ...btnStyle("ghost"), height: 38, marginBottom: 2 }} onClick={() => setSetupStep(0)}>Cancel</button>
                  </div>
                </div>
              </div>
            )}
          </div>
        )}
      </SectionCard>
    </div>
  );
}
